### ISSUE TITLE
Was 2.0.0 yanked on purpose?

### ISSUE THREAD

**Issue by ehrw1n** [talesluna/rust-printers#26]
Is there a reason for concern regarding a potential supply chain attack, or was the yanking of all crate versions prior to yesterday's 2.1.0-rc1 an intentional action on your part? I've also noticed that the crate size has increased significantly, more than doubling in size. Given that the only version currently available is a release candidate, it's not possible to add it to a project without explicitly opting into a prerelease version.

**Comment by talesluna** [comment]
Hi @ehrw1n 

I decided to yank version 2.0.0 because I understand that 2.1.0-rc is already mature enough and fixes some issues like 22. But i unyank 2.0.0 until 2.1.0 being defintive, which should be soon.

About the size, I tried to keep the lib as small as possible but there is the cost of trying to create a better structure for the project with two platforms unix/cups and windows/winspool. I consider that despite the increase, 20kb is acceptable for most use cases that have memory limitations.
